name: Push to docker hub

on:
  workflow_dispatch:
    inputs:
      last_tag:
        description: "Last generated semantic tag"
        required: false
        type: string
        default: ""
  workflow_call:
    inputs:
      last_tag:
        description: "Last generated semantic tag"
        required: false
        type: string
        default: ""
    secrets:
      SONAR_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - id: "api"
            name: "homebudget-accounting-api"
            file: "dockerfile"
            context: "."
          - id: "payments-consumer-worker"
            name: "homebudget-accounting-payments-consumer-worker"
            file: "HomeBudget.Accounting.Workers.OperationsConsumer/dockerfile"
            context: "."

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image - ${{ matrix.service.id }}
        env:
          BUILD_VERSION: ${{ inputs.last_tag }}
        run: |
          docker build \
            --target final \
            -f "${{ matrix.service.file }}" \
            -t "${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:${{ inputs.last_tag }}" \
            "${{ matrix.service.context }}"

      - name: Push Docker Image - ${{ matrix.service.id }}
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:${{ inputs.last_tag }}"
